variable "resource_group_rg" {}
variable "resource_group_rg1" {}
variable "rg_name" {}
variable "rg1_name" {}
variable "location" {}
variable "hub_vn" {}
variable "subnets" {}
variable "spoke_rg" {}
variable "address_space" {}
varialbe "mgmt_sn" {}
varialbe "public_ip_name" {} 
varialbe "allocation_method" {} 
varialbe "nic_name" {}
varialbe "ip_config_name" {}
varialbe "private_ip_allocation" {}
varialbe "vm_name" {}
varialbe "size" {}
varialbe "admin_username" {}
varialbe "pub_ssh_key" {} 
varialbe "disk_caching" {}
varialbe "storage_account_type" {}
varialbe "publisher" {}
varialbe "offer" {}
varialbe "sku" {}
varialbe "version" {}