variable "resource_group_rg" {}
variable "resource_group_rg1" {}
variable "rg_name" {}
variable "rg1_name" {}
variable "location" {}
variable "hub_vn" {}
variable "subnets" {}
variable "spoke_rg" {}
variable "address_space" {}
variable "dns_servers" {}
variable "mgmt_sn" {}
variable "public_ip_name" {} 
variable "private_ip_address" {}
variable "allocation_method" {} 
variable "nic_name" {}
variable "ip_config_name" {}
variable "private_ip_allocation" {}
variable "vm_name" {}
variable "size" {}
variable "admin_username" {}
variable "pub_ssh_key" {} 
variable "disk_caching" {}
variable "storage_account_type" {}
variable "publisher" {}
variable "offer" {}
variable "sku" {}
variable "img_version" {}