name: Bust-A-Cluster

on:
  workflow_dispatch:
  workflow_call:

env:
  RESOURCE_GROUP: "dank_simple_cluster_resources"
  CLUSTER_NAME: "aks-dank_prime"

jobs:
  kubetime:
    continue-on-error: true
    strategy:
      matrix:
        rg: 
          - dank_simple_cluster_prime
          - dank_simple_cluster_resources_beta
        cluster:
          - dank-aks_prime
          - dank-aks_beta
        env: 
          - prime
          - beta
        include:
          - rg: dank_simple_cluster_prime
            cluster: dank-aks_prime
            env: prime
          - rg: dank_simple_cluster_beta
            cluster: dank-aks_beta
            env: beta
    environment:
      name: ${{ matrix.env }}
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ matrix.rg }}
        cluster-name: ${{ matrix.cluster }}
        
    - name: Install Kubelogin
      run: |
        curl -L $(curl -s https://api.github.com/repos/Azure/kubelogin/releases/latest \
          | jq -r ".assets[] | select(.name | test(\"linux-amd64.zip$\")) | .browser_download_url") \
          -o kubelogin.zip
        unzip kubelogin.zip
        chmod +x bin/linux_amd64/kubelogin
        echo "$(find "$(pwd)" -name kubelogin | rev | cut -d '/' -f 2- | rev)" >> $GITHUB_PATH
        
    - name: Create Namespace and Secret
      run: |
        kubelogin convert-kubeconfig -l azurecli
        kubectl create ns actions-runner-system
        kubectl create secret generic controller-manager \
          -n actions-runner-system \
          --from-literal=github_token=${{ secrets.ARC_PAT }}

    - name: Install Cert Manager
      run: |
        helm repo add jetstack https://charts.jetstack.io
        helm repo update
        helm install \
          cert-manager jetstack/cert-manager \
          --namespace cert-manager \
          --create-namespace \
          --version v1.9.1 \
          --set installCRDs=true

    - name: Install Actions Runner Controller
      run: |
        helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
        helm upgrade --install --namespace actions-runner-system \
          --wait actions-runner-controller actions-runner-controller/actions-runner-controller

    - name: Apply Manifests
      run: |
        echo "Nothing done if no manifests here"
        if [ ! -d manifests ]; then
          kubectl apply -f manifests
        fi