name: 'Terraform Nuke'

on:
  workflow_dispatch:
    inputs:
      cluster-type:
        type: choice
        description: Which Cluster to build?
        options:
        - aks-simple
        - aks-rbac
        - aks-private-calico
        - aks-keyvault
  workflow_call:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  nuke:
    continue-on-error: true
    strategy:
      matrix: 
        env: [prime, beta]
    environment:
      name: ${{ matrix.env }}
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: aks/${{ inputs.cluster-type }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Destroy
      run: |
        terraform init -backend-config=key=${{ matrix.env  }}
        terraform destroy -var-file=env/${{ matrix.env }}.tfvars -var="pub_ssh_key=${{secrets.PUB_SSH_KEY}}" -input=false -auto-approve
