name: 'Terraform Nuke'

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  clean:
    strategy:
      matrix:
        target: [prime, beta]
    uses: ./.github/workflows/runner-cleanup.yml
    with:
      target: ${{ matrix.target }}
    secrets: inherit
  
  nuke:
    continue-on-error: true
    strategy:
      matrix: 
        env: [prime, beta]
    environment:
      name: ${{ matrix.env }}
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: aks/aks-simple

    steps:
    - name: Checkout
      uses: actions/checkout@v3

#     - name: Terraform Destroy
#       run: |
#         terraform init -backend-config=key=${{ matrix.env  }}
#         terraform destroy -var-file=env/${{ matrix.env }}.tfvars -var="pub_ssh_key=${{secrets.PUB_SSH_KEY}}" -input=false -auto-approve
