name: 'Terraform Apply'

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  apply:
    continue-on-error: true
    strategy:
      matrix: 
        env: [prime, beta]
    environment:
      name: ${{ matrix.env }}
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: aks/aks-simple

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Apply
      run: |
        terraform init -backend-config=key=${{ matrix.env  }}
        terraform apply -var-file=env/${{ matrix.env }}.tfvars -input=false -auto-approve
